name: Sync To Gitee
on: [ push, delete, create ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/YuzukiHD
        dst: gitee/YuzukiHD-Mirror
        dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        account_type: org
        white_list: "TinyVision"
